spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
#    correlated leads to channel churn but with template.invoke it doesn't. Why?
    publisher-confirm-type: simple
    publisher-returns: true